server:
  port: 8080


#   数据相关配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/upload_files?serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root


#  mybatis
mybatis:
  mapper-locations: mappers/files/*.xml
  type-aliases-package: com.uploadfiles.pojo


#  图上存储路径
files_url:
  upload_url: \uploadfiles\src\main\resources\static\images\



#   日志在控制台显示
logging:
  level:
    root: info
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%5.15t]){faint} %yellow(at %class.%method) \\(%file:%line\\)%clr(:) %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
